# Generated by Django 3.1.3 on 2020-11-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('postal', models.IntegerField(default=0)),
                ('employeesc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DataDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=200)),
                ('recommendations', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prms.company')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lasVisit', models.DateField(verbose_name='Last Visit')),
                ('nextVisit', models.DateField(verbose_name='Next Visit')),
                ('healthstuff', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prms.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prms.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('postal', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('outstanding', models.IntegerField(default=0)),
                ('lastInvoive', models.DateField(verbose_name='Last Invoice')),
                ('nextInvoice', models.DateField(verbose_name='Next Invoice')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prms.company')),
            ],
        ),
    ]
