# Generated by Django 3.1.3 on 2020-12-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0003_auto_20201130_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybilling',
            old_name='lastInvoive',
            new_name='lastInvoice',
        ),
        migrations.AlterField(
            model_name='employees',
            name='group',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('PRACTITIONER', 'Practitioner'), ('USER', 'User')], default='User', max_length=12),
        ),
    ]
