# Generated by Django 3.1.3 on 2021-01-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0005_auto_20210118_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldata',
            name='lasVisit',
        ),
        migrations.RemoveField(
            model_name='medicaldata',
            name='nextVisit',
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Booking date&time')),
                ('reason', models.CharField(max_length=200)),
                ('prognosis', models.CharField(max_length=1000)),
                ('notes', models.CharField(max_length=1000)),
                ('perscription', models.BooleanField()),
                ('files', models.FileField(upload_to='')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prms.employees')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prms.patients')),
            ],
        ),
    ]
