# Generated by Django 3.1.3 on 2021-01-27 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0007_auto_20210126_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldata',
            name='healthstuff',
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='chronicIllness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='chronicIllnessNotes',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='familyCancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='familyCancerNotes',
            field=models.CharField(blank=True, default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='medication',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='otherNotes',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='pastSurgery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='pastSurgeryNotes',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.CharField(default='JHB', max_length=200),
        ),
        migrations.AddField(
            model_name='patients',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='patients',
            name='idNumber',
            field=models.CharField(default='0000', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='maidName',
            field=models.CharField(blank=True, default='Basic', max_length=25),
        ),
        migrations.AddField(
            model_name='patients',
            name='maidNumber',
            field=models.CharField(blank=True, default='0000', max_length=15),
        ),
        migrations.AddField(
            model_name='patients',
            name='medicalAid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
