# Generated by Django 3.1.3 on 2021-02-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prms', '0009_medicaldata_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='date',
            field=models.DateTimeField(verbose_name='Visit date'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='notes',
            field=models.CharField(blank=True, default='N/A', max_length=1000),
        ),
    ]
